on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy with github-pages
    uses: Camila-Ribeiro/github-pages-deploy-action@master
    env:
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: target # The folder the action should deploy.
        env.url: ${{ secrets.URL }}
        env.username: ${{ secrets.USERNAME }}
        env.password: ${{ secrets.PASSWORD }}