on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy with github-pages
      uses: Camila-Ribeiro/phorest-techtest-camilaRibeiro@master
      env:
        env.url: ${{ secrets.URL }}
        env.username: ${{ secrets.USERNAME }}
        env.password: ${{ secrets.PASSWORD }}