on:
push:
    branches:
    - master

jobs:
build:

    runs-on: ubuntu-latest

    steps:
    env:
      env.url: ${{ secrets.url }}
      env.username: ${{ secrets.username }}
      env.password: ${{ secrets.password }}
